# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [2]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [3]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [4]:
x.shape, y.shape

((20,), (20,))

In [33]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 모델의 시작과 끝을 지정
model = keras.models.Model(il, ol)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')
#metrics에서는 선형회귀에서 선언 xxx

In [34]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 291ms/step - loss: 503.0535
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 502.5368
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 502.0203
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 501.5042
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 500.9883
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 500.4727
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 499.9575
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 499.4426
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 498.9279
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 498.4137


In [7]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[ 0.00999833 -0.22951284 -0.469024   -0.7085352  -0.9480463  -1.1875575
 -1.4270687  -1.6665798  -1.906091   -2.1456022  -2.3851132  -2.6246245
 -2.8641357  -3.1036468  -3.343158   -3.582669   -3.8221803  -4.0616913
 -4.301203   -4.540714  ]


## Now, Your turn!

In [14]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [15]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [22]:
x.shape, y.shape

((20,), (20,))

In [30]:
## Functional API

# 1.세션 클리어 
keras.backend.clear_session()

# 2. 레이어 사슬 연결
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 3. 모델의 시작과 끝을 지정 
model=keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4.컴파일
model.compile(loss='mse',optimizer='adam')

In [31]:
model.fit(x,y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 275ms/step - loss: 199.0551
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 198.7467
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 198.4386
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 198.1308
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 197.8233
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 197.5161
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 197.2092
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 196.9027
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 196.5965
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 196.2906


In [29]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]
[ -0.0199921  -1.0690078  -2.1180234  -3.1670392  -4.2160544  -5.26507
  -6.314086   -7.3631015  -8.412117   -9.461133  -10.510148  -11.559164
 -12.60818   -13.657195  -14.706211  -15.755226  -16.804243  -17.853258
 -18.902275  -19.95129  ]


## Quick Logistic Regression!

In [10]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [11]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [12]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [13]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 0s 420ms/step - loss: 6.3281 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 6.3205 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 6.3128 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 6.3052 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 6.2975 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 6.2899 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 6.2823 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 6.2746 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 6.2670 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 6.2593 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 

## Now, Your turn!

In [14]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
