# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [5]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
x.shape, y.shape

((20,), (20,))

In [7]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 모델의 시작과 끝을 지정
model = keras.models.Model(il, ol)

# 컴파일 해주렴
#adsfsdf
model.compile(loss = 'mse', optimizer = 'adam')
#metrics에서는 선형회귀에서 선언 xxx

In [8]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 335ms/step - loss: 229.0013
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 228.6400
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 228.2790
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 227.9182
Epoch 5/10
1/1 [==============================] - 0s 3ms/step - loss: 227.5578
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 227.1977
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 226.8379
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 226.4784
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 226.1193
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 225.7605


In [9]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[9.9973017e-03 5.8215958e-01 1.1543218e+00 1.7264841e+00 2.2986465e+00
 2.8708086e+00 3.4429710e+00 4.0151334e+00 4.5872955e+00 5.1594577e+00
 5.7316198e+00 6.3037825e+00 6.8759446e+00 7.4481068e+00 8.0202694e+00
 8.5924311e+00 9.1645937e+00 9.7367563e+00 1.0308918e+01 1.0881081e+01]


## Now, Your turn!

In [10]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [11]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [12]:
x.shape, y.shape

((20,), (20,))

In [13]:
## Functional API

# 1.세션 클리어 
keras.backend.clear_session()

# 2. 레이어 사슬 연결
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 3. 모델의 시작과 끝을 지정 
model=keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4.컴파일
model.compile(loss='mse',optimizer='adam')

NameError: name 'input_layer' is not defined

In [ ]:
model.fit(x,y, epochs=10, verbose=1)

In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [ ]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)